(() => {
'use strict';
const D=window.LWC_DATA, C=D.cards, W=D.wrestlers;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let state=null, selected='austin';
const screens=['menu','select','match','result'];
function show(id){screens.forEach(x=>$('#'+x).classList.toggle('active',x===id));window.scrollTo(0,0)}
function clamp(n,a,b){return Math.max(a,Math.min(b,n))}
function other(id){return id==='austin'?'rock':'austin'}
function weightedLibrary(id){const base=W[id].library.flatMap(k=>['cover','hookLeg','rollUp','stunner','rockBottom','peoplesElbow','austinComeback','rockComeback'].includes(k)?[k]:[k,k]);return base}
function makeFighter(id){return {id,health:100,momentum:0,hand:[],discard:[],usedOnce:new Set(),guard:0,redraw:true,combo:null,lastCard:null}}
function startMatch(playerId){selected=playerId;state={player:makeFighter(playerId),cpu:makeFighter(other(playerId)),position:'standing',setup:null,crowd:0,control:50,turn:0,phase:'Opening',log:[],ended:false,nearFalls:0,variety:new Set(),finishers:0};drawToFive(state.player);drawToFive(state.cpu);renderMatch();show('match');say(`${W[state.player.id].name} faces ${W[state.cpu.id].name}. The bell rings.`)}
function drawCard(f){let pool=weightedLibrary(f.id).filter(k=>canEverDraw(k,f));if(!pool.length)pool=['punch'];let attempts=0,k;do{k=pool[Math.floor(Math.random()*pool.length)];attempts++}while(attempts<20&&f.hand.filter(x=>x===k).length>=2);return k}
function canEverDraw(k,f){const card=C[k];if(card.once&&f.usedOnce.has(k))return false;if(card.finisher&&(state.turn<4||f.momentum<24))return false;if(card.type==='Pin'&&state.turn<2)return false;if(card.onlyBehind&&f.health>=stateOpponent(f).health-12)return false;return true}
function stateOpponent(f){return f===state.player?state.cpu:state.player}
function drawToFive(f){while(f.hand.length<5)f.hand.push(drawCard(f));ensurePlayable(f)}
function ensurePlayable(f){
  if(f.hand.some(k=>playability(k,f).ok))return false;
  // Prevent dead hands after the opponent changes the ring position.
  // Brace and Block is always legal, costs no momentum and lets play continue.
  let replace=f.hand.findIndex(k=>!C[k].once);
  if(replace<0)replace=0;
  f.hand[replace]='block';
  return true;
}
function reqMatches(){return true}
function phaseAllows(card){if(card.finisher&&state.phase==='Opening')return false;return true}
function playability(k,f){const card=C[k],opp=stateOpponent(f);if(card.cost>f.momentum)return{ok:false,why:`Needs ${card.cost} momentum`};if(card.once&&f.usedOnce.has(k))return{ok:false,why:'Already used'};if(card.onlyBehind&&f.health>=opp.health-12)return{ok:false,why:'Only available when badly behind'};if(!phaseAllows(card))return{ok:false,why:'Unavailable in the opening'};return{ok:true,why:''}}
function effectiveAccuracy(card,f,opp){let a=card.accuracy;if(card.type==='Grapple'||card.tags?.includes('grapple'))a+=(W[f.id].stats.technique-W[opp.id].stats.technique)*.12;if(card.type==='Strike')a+=(W[f.id].stats.brawling-W[opp.id].stats.brawling)*.1;if(card.type==='Signature'&&f.id==='rock')a*=W.rock.traits.signatureAccuracy;if(f.health<35)a-=6;if(opp.guard)a-=opp.guard*30;if(f.combo===card.name||f.combo===card.id)a+=10;return clamp(Math.round(a),35,98)}
function cardDamage(card,f,critical=false){let d=card.damage;if(card.type==='Strike'&&f.id==='austin')d*=W.austin.traits.strikeDamage;if(state.phase==='Finishing')d*=1.08;if(critical)d*=1.25;return Math.round(d)}
function pinChance(f,opp,card){let chance=(100-opp.health)*.68+card.pinBonus+(f.momentum*.08)-(opp.momentum*.05)+(W[f.id].stats.power-W[opp.id].stats.resilience)*.15;if(card.surprise)chance+=10;if(f.lastCard&&C[f.lastCard]?.finisher)chance+=C[f.lastCard].pinBonus||25;return clamp(Math.round(chance),4,94)}
function useCard(index,actor,isCpu=false){if(state.ended)return;const key=actor.hand[index],card=C[key],opp=stateOpponent(actor),p=playability(key,actor);if(!p.ok){if(!isCpu)say(p.why);return false}actor.hand.splice(index,1);actor.discard.push(key);actor.momentum=clamp(actor.momentum-card.cost,0,100);if(card.once)actor.usedOnce.add(key);state.variety.add(key);if(card.type==='Pin'){resolvePin(actor,opp,card);finishTurn(actor,isCpu);return true}
let acc=effectiveAccuracy(card,actor,opp);const roll=Math.random()*100;const landed=roll<=acc;const critical=landed&&roll<=Math.max(5,acc*.12);if(landed){let dmg=cardDamage(card,actor,critical);if(opp.guard){dmg=Math.round(dmg*(1-opp.guard));opp.guard=0}opp.health=clamp(opp.health-dmg,0,100);let gain=card.momentum||0;if(actor.id==='austin'&&card.tags?.includes('aggressive'))gain*=W.austin.traits.crowdFromAggression;if(actor.combo&&actor.id==='rock')gain*=W.rock.traits.comboMomentum;actor.momentum=clamp(actor.momentum+Math.round(gain),0,100);if(card.heal)actor.health=clamp(actor.health+card.heal,0,100);if(card.crowd){let cg=card.crowd;if(actor.id==='rock')cg*=W.rock.traits.crowdGain;state.crowd=clamp(state.crowd+Math.round(cg),0,100)}else state.crowd=clamp(state.crowd+Math.round((dmg+gain)/5),0,100);if(card.guard)actor.guard=card.guard;if(card.result!=='same')state.position=card.result;if(card.setup)state.setup=card.setup;else if(card.type!=='Control')state.setup=null;actor.combo=card.combo?C[card.combo]?.name:null;actor.lastCard=key;if(card.finisher){state.finishers++;actor.combo=null}const swing=Math.round((dmg+gain*.4)/4);state.control=clamp(state.control+(actor===state.player?swing:-swing),5,95);say(`${W[actor.id].shortName} ${critical?'lands a critical ': 'uses '}${card.name}${dmg?` for ${dmg} damage`:''}.`);if(card.finisher&&opp.health<55)setTimeout(()=>offerAutoPin(actor,opp,card,isCpu),350)}else{let loss=card.riskMomentum||Math.round(card.cost*.45);if(actor.id==='austin')loss=Math.round(loss*W.austin.traits.riskPenalty);actor.momentum=clamp(actor.momentum-loss,0,100);opp.momentum=clamp(opp.momentum+6,0,100);state.control=clamp(state.control+(actor===state.player?-6:6),5,95);say(`${W[opp.id].shortName} blocks or counters ${card.name}. ${W[actor.id].shortName} loses ${loss} momentum.`)}
updatePhase();finishTurn(actor,isCpu);return true}
function offerAutoPin(actor,opp,card,isCpu){if(state.ended)return;if(isCpu&&Math.random()<.65){resolvePin(actor,opp,{...C.cover,pinBonus:card.pinBonus});renderMatch()}}
function resolvePin(actor,opp,card){const chance=pinChance(actor,opp,card);const roll=Math.random()*100;state.nearFalls++;if(roll<=chance){say(`${W[actor.id].shortName} makes the cover — the probability was ${chance}%. Three count!`);endMatch(actor)}else{const count=roll<chance+18?'2.9':roll<chance+38?'2':'1';opp.momentum=clamp(opp.momentum+10,0,100);state.crowd=clamp(state.crowd+8,0,100);say(`${W[actor.id].shortName} covers with a ${chance}% chance, but ${W[opp.id].shortName} kicks out at ${count}!`)}}
function finishTurn(actor,isCpu){if(state.ended)return;drawToFive(actor);state.turn++;updatePhase();renderMatch();if(actor===state.player&&!isCpu){$('#turnLabel').textContent='Opponent thinking…';setTimeout(cpuTurn,700)}else{$('#turnLabel').textContent='Your turn'}}
function cpuTurn(){if(state.ended)return;const f=state.cpu,opp=state.player;let options=f.hand.map((k,i)=>({k,i,p:playability(k,f),score:0})).filter(x=>x.p.ok);if(!options.length){ensurePlayable(f);options=f.hand.map((k,i)=>({k,i,p:playability(k,f),score:0})).filter(x=>x.p.ok)}options.forEach(o=>{const c=C[o.k];o.score=(c.damage||0)*1.4+(c.momentum||0)+Math.random()*20;if(c.type==='Pin')o.score=pinChance(f,opp,c)>45?90:5;if(c.finisher&&opp.health<55)o.score+=70;if(c.onlyBehind)o.score+=45;if(c.result==='corner'&&f.id==='austin')o.score+=18;if(c.name==='Spinebuster'&&f.id==='rock')o.score+=18});options.sort((a,b)=>b.score-a.score);useCard(options[0].i,f,true)}
function updatePhase(){const avg=(state.player.health+state.cpu.health)/2;if(state.turn>=12||avg<55)state.phase='Finishing';else if(state.turn>=5||avg<78)state.phase='Middle';else state.phase='Opening'}
function redraw(){if(!state.player.redraw)return;say('You redraw your entire hand.');state.player.hand=[];state.player.redraw=false;drawToFive(state.player);renderMatch()}
function endMatch(winner){state.ended=true;const loser=stateOpponent(winner);const base=1.5+Math.min(2,state.turn/8)+Math.min(.75,state.variety.size/20)+Math.min(.5,state.nearFalls*.12)+Math.min(.5,state.finishers*.12)+state.crowd/250;const stars=Math.round(clamp(base,1,5)*2)/2;$('#winnerPortrait').src=W[winner.id].portrait;$('#winnerName').textContent=`${W[winner.id].name} wins` ;$('#resultSummary').textContent=`${W[loser.id].shortName} was defeated after ${state.turn} card plays. The match featured ${state.variety.size} different cards and ${state.nearFalls} pin attempt${state.nearFalls===1?'':'s'}.`;$('#rating').textContent='★'.repeat(Math.floor(stars))+(stars%1?'½':'')+`  ${stars.toFixed(1)}`;setTimeout(()=>show('result'),650)}
function say(t){state.log.unshift(t);state.log=state.log.slice(0,14);$('#message').textContent=t;renderLog()}
function renderLog(){$('#log').innerHTML=state.log.map(t=>`<div>${t}</div>`).join('')}
function renderMatch(){const p=state.player,c=state.cpu;ensurePlayable(p);$('#playerPortrait').src=W[p.id].portrait;$('#cpuPortrait').src=W[c.id].portrait;$('#playerName').textContent=W[p.id].name;$('#cpuName').textContent=W[c.id].name;[['player',p],['cpu',c]].forEach(([pre,f])=>{$(`#${pre}HealthText`).textContent=f.health; $(`#${pre}HealthBar`).style.width=f.health+'%';$(`#${pre}MomentumText`).textContent=f.momentum;$(`#${pre}MomentumBar`).style.width=f.momentum+'%'});$('#playerControl').textContent=state.control;$('#cpuControl').textContent=100-state.control;$('#controlBar').style.width=state.control+'%';$('#position').textContent=state.setup?`Position: ${state.position} · Setup: ${state.setup}`:`Position: ${state.position}`;$('#crowd').textContent=`Crowd ${state.crowd}`;$('#phaseBadge').textContent=state.phase;$('#redrawBtn').disabled=!p.redraw;renderHand();renderLog()}
function renderHand(){const f=state.player;$('#hand').innerHTML=f.hand.map((k,i)=>{const c=C[k],p=playability(k,f),acc=effectiveAccuracy(c,f,state.cpu);const req='Playable now';const combo=f.combo===c.name?'<div class="combo">COMBO READY · +10% accuracy</div>':c.combo?`<div class="combo">Sets up ${C[c.combo].name}</div>`:'';return `<button class="gameCard ${p.ok?'':'unplayable'}" data-card="${i}" ${p.ok?'':'disabled'}><span class="type">${c.type}</span><h4>${c.name}</h4><div class="requirement">${p.ok?req:p.why}</div>${combo}<div class="cardStats"><div class="cardStat"><span>Damage</span><b>${c.damage}</b></div><div class="cardStat"><span>Momentum</span><b>${c.momentum>=0?'+':''}${c.momentum}</b></div><div class="cardStat"><span>Cost</span><b>${c.cost}</b></div><div class="cardStat"><span>Accuracy</span><b>${acc}%</b></div></div>${c.finisher?`<div class="risk">Counter risk: lose ${c.riskMomentum} momentum</div>`:''}</button>`}).join('');$$('[data-card]').forEach(b=>b.addEventListener('click',()=>useCard(Number(b.dataset.card),state.player,false)))}
function renderRoster(){$('#roster').innerHTML=Object.values(W).map(w=>`<button class="rosterCard" data-w="${w.id}"><img src="${w.portrait}"><div class="rosterInfo"><h3>${w.name}</h3><p>${w.era} persona</p><div class="stats"><span>Power ${w.stats.power}</span><span>Speed ${w.stats.speed}</span><span>Brawling ${w.stats.brawling}</span><span>Technique ${w.stats.technique}</span><span>Ring IQ ${w.stats.ringIQ}</span><span>Resilience ${w.stats.resilience}</span></div></div></button>`).join('');$$('[data-w]').forEach(b=>b.onclick=()=>startMatch(b.dataset.w))}
$('#startBtn').onclick=()=>{renderRoster();show('select')};$('#quitBtn').onclick=()=>show('menu');$('#redrawBtn').onclick=redraw;$('#rematchBtn').onclick=()=>startMatch(selected);$$('[data-back]').forEach(b=>b.onclick=()=>show(b.dataset.back));
})();
