const vm=require('vm'),fs=require('fs');const ctx={window:{}};vm.createContext(ctx);vm.runInContext(fs.readFileSync(__dirname+'/data.js','utf8'),ctx);const D=ctx.window.LWC_DATA,C=D.cards,W=D.wrestlers;
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),shuffle=a=>a.sort(()=>Math.random()-.5),ids=Object.keys(W);
const rev=k=>C[k]?.type==='Reversal', action=k=>C[k]?.type==='Action';
function cat(c){if(c.type==='Aerial'||c.tags?.includes('aerial'))return'Aerial';if(c.type==='Submission'||c.tags?.includes('submission'))return'Submission';if(c.type==='Control'||c.tags?.includes('control'))return'Control';if(c.type==='Strike'||c.tags?.includes('strike'))return'Strike';return'Grapple'}
function counter(k,a){return C[k]?.counter===a||(rev(k)&&C[k].reverse===cat(C[a]))}
function fighter(id){return{id,h:100,m:0,hand:[],deck:shuffle(W[id].library.filter(k=>C[k]?.type!=='Pin').slice()),discard:[],last:null,chain:0,action:false}}
function recycle(f){if(!f.deck.length){f.deck=shuffle(f.discard.splice(0))}}
function draw(f,p){recycle(f);let i=p?f.deck.findIndex(p):0;if(i<0)i=0;if(!f.deck.length)return;f.hand.push(f.deck.splice(i,1)[0])}
function opening(f){draw(f,k=>(C[k].cost||0)===0&&!rev(k)&&!action(k));draw(f,k=>(C[k].cost||0)===0&&!rev(k)&&!action(k));draw(f,k=>cat(C[k])==='Grapple'&&!rev(k)&&!action(k));draw(f,rev);draw(f)}
function playable(k,f,phase){let c=C[k];return c&&!rev(k)&&(c.cost||0)<=f.m&&!(action(k)&&f.action)&&!(c.finisher&&phase==='Opening')}
function use(f,i){let k=f.hand.splice(i,1)[0];f.discard.push(k);draw(f);return k}
function pinChance(a,o){let ch=(100-o.h)*.78+(a.m*.08)-(o.m*.04)+(W[a.id].stats.power-W[o.id].stats.resilience)*.14;if(C[a.last]?.finisher)ch+=C[a.last].pinBonus||30;if(o.h<=0)ch=98;return clamp(ch,5,98)}
function match(){let a=fighter(ids[0]),b=fighter(ids[1]),actor=Math.random()<.5?a:b,opp=actor===a?b:a,turn=0,near=0,finishers=0,maxHand=5;opening(a);opening(b);while(turn<100){let phase=turn>=18||(a.h+b.h)/2<50?'Finishing':turn>=7||(a.h+b.h)/2<78?'Middle':'Opening';if((opp.h<=38||C[actor.last]?.finisher||turn>=45)&&Math.random()<.65){near++;turn++;if(Math.random()*100<=pinChance(actor,opp))return{turn,near,maxHand,winner:actor.id};opp.h=Math.max(opp.h,6);opp.m=clamp(opp.m+12,0,100);[actor,opp]=[opp,actor];actor.chain=opp.chain=0;actor.action=opp.action=false;continue}
 let opts=actor.hand.map((k,i)=>({k,i})).filter(x=>playable(x.k,actor,phase));if(!opts.length){draw(actor,k=>(C[k].cost||0)===0&&!rev(k));opts=actor.hand.map((k,i)=>({k,i})).filter(x=>playable(x.k,actor,phase));if(!opts.length){[actor,opp]=[opp,actor];continue}}
 opts.forEach(x=>{let c=C[x.k];x.s=(c.damage||0)*1.5+(c.momentum||0)+Math.random()*10+(c.finisher&&opp.h<45?70:0)});opts.sort((x,y)=>y.s-x.s);let key=use(actor,opts[0].i),c=C[key];let ri=opp.hand.findIndex(k=>counter(k,key)&&(C[k].cost||0)<=opp.m);if(!action(key)&&ri>=0){let rk=use(opp,ri),rc=C[rk];opp.m=clamp(opp.m-(rc.cost||0)+(rc.momentum||0),0,100);actor.h=clamp(actor.h-(rc.damage||0),0,100);draw(actor);turn++;[actor,opp]=[opp,actor];actor.chain=opp.chain=0;actor.action=opp.action=false;continue}
 actor.m=clamp(actor.m-(c.cost||0)+(c.momentum||0),0,100);opp.h=clamp(opp.h-(c.damage||0),0,100);if(c.damage)draw(opp,actor.chain>=3?k=>counter(k,key):null);if(action(key))actor.action=true;actor.last=key;actor.chain++;if(c.finisher)finishers++;turn++;maxHand=Math.max(maxHand,a.hand.length,b.hand.length);if(turn>=60)return{turn,near,maxHand,winner:actor.id,stoppage:true}}
 return{turn,near,maxHand,failed:true}}
let out=[];for(let i=0;i<10000;i++)out.push(match());console.log({finished:out.filter(x=>!x.failed).length,avgTurns:out.reduce((s,x)=>s+x.turn,0)/out.length,avgNear:out.reduce((s,x)=>s+x.near,0)/out.length,maxHand:Math.max(...out.map(x=>x.maxHand)),stoppages:out.filter(x=>x.stoppage).length,winners:ids.map(id=>[id,out.filter(x=>x.winner===id).length])});
